#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.6 on Sun Aug  2 14:21:54 2020
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Frame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Frame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((600, 180))
        self.notebook_1 = wx.Notebook(self, wx.ID_ANY)
        self.pane_1 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.text_ctrl_inputfile = wx.TextCtrl(
            self.pane_1, wx.ID_ANY, "Caminho do arquivo", style=wx.TE_PROCESS_ENTER)
        self.button_inputfile = wx.Button(self.pane_1, wx.ID_OPEN, "")
        self.window_1 = ProgressWidget(self.pane_1, wx.ID_ANY)
        self.pane_2 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.frame_statusbar = self.CreateStatusBar(2)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_TEXT_ENTER, self.getPath, self.text_ctrl_inputfile)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Frame.__set_properties
        self.SetTitle("PdFind")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap(
            "D:\\ARQUIVOS PESSOAIS\\GitHub\\PdFind\\ui\\search.png", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.frame_statusbar.SetStatusWidths([-1, 0])

        # statusbar fields
        frame_statusbar_fields = ["frame_statusbar", "dede"]
        for i in range(len(frame_statusbar_fields)):
            self.frame_statusbar.SetStatusText(frame_statusbar_fields[i], i)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Frame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.StaticBoxSizer(wx.StaticBox(
            self.pane_1, wx.ID_ANY, "Selecione o arquivo"), wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(self.text_ctrl_inputfile, 6, wx.ALL |
                    wx.EXPAND | wx.FIXED_MINSIZE, 5)
        sizer_3.Add(self.button_inputfile, 1,
                    wx.ALIGN_CENTER_VERTICAL | wx.ALL | wx.FIXED_MINSIZE, 5)
        sizer_4.Add(sizer_3, 0, 0, 0)
        sizer_2.Add(sizer_4, 0, wx.EXPAND, 0)
        sizer_2.Add(self.window_1, 1, wx.ALL | wx.EXPAND, 2)
        self.pane_1.SetSizer(sizer_2)
        self.notebook_1.AddPage(self.pane_1, "Aplicativo")
        self.notebook_1.AddPage(self.pane_2, u"Configurações")
        sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def getPath(self, event):  # wxGlade: Frame.<event_handler>
        print("Event handler 'getPath' not implemented!")
        event.Skip()

# end of class Frame


class MyApp(wx.App):
    def OnInit(self):
        self.frame = Frame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp
class ProgressWidget(wx.Gauge):
    def __init__(self):
        super().__init__(range=100, style=wx.GA_HORIZONTAL)

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
