# Generated by Django 3.1.2 on 2020-10-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_pdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='data',
            field=models.FileField(default=' ', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
