# Generated by Django 3.1.2 on 2020-10-10 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convert_pdf', '0002_file_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='data',
            new_name='upload',
        ),
    ]
